services:
  app: 
    build:
      dockerfile: Dockerfile.local
    container_name: onion-architecture-app
    depends_on: 
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV=local-docker
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - ./:/app

  mysql:
    image: mysql:latest
    container_name: onion-architecture-mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - my-network

volumes:
  mysql:

networks:
  my-network:


